package com.dataanalyse.workflow.engine;

import java.util.*;

/** 条件分支轻量表达式求值器，不依赖脚本引擎。 */
public final class ConditionEvaluator {
    private ConditionEvaluator(){}
    public static boolean eval(String expression,Object input,Map<String,Object> nodeContext,Map<String,Object> contextParams){if(expression==null||expression.isBlank())return true;String rendered=render(expression,text(input),nodeContext,contextParams);for(String orPart:split(rendered,"or")){boolean all=true;for(String andPart:split(orPart,"and"))all=all&&compare(andPart.trim());if(all)return true;}return false;}
    private static boolean compare(String expression){Operator op=findOperator(expression);if(op==null)throw new IllegalArgumentException("条件表达式格式不正确："+expression);String left=value(expression.substring(0,op.index)),right=value(expression.substring(op.index+op.token.length()));if("contains".equals(op.name))return left.contains(right);if("not contains".equals(op.name))return !left.contains(right);Double ln=number(left),rn=number(right);int compared=ln!=null&&rn!=null?Double.compare(ln,rn):left.compareTo(right);return switch(op.name){case "=="->ln!=null&&rn!=null?compared==0:left.equals(right);case "!="->ln!=null&&rn!=null?compared!=0:!left.equals(right);case ">"->compared>0;case ">="->compared>=0;case "<"->compared<0;case "<="->compared<=0;default->false;};}
    private static Operator findOperator(String expression){String[] words={"not contains","contains"};for(String token:words){int i=indexOfToken(expression,token);if(i>=0)return new Operator(token,i,token);}String[] symbols={">=","<=","==","!=",">","<"};for(String token:symbols){int i=indexOutsideQuotes(expression,token);if(i>=0)return new Operator(token,i,token);}return null;}
    private static List<String> split(String expression,String keyword){List<String> parts=new ArrayList<>();int start=0;char quote=0;for(int i=0;i<=expression.length()-keyword.length();i++){char ch=expression.charAt(i);if((ch=='\''||ch=='\"')&&(i==0||expression.charAt(i-1)!='\\')){quote=quote==0?ch:quote==ch?0:quote;continue;}if(quote==0&&expression.regionMatches(true,i,keyword,0,keyword.length())&&boundary(expression,i-1)&&boundary(expression,i+keyword.length())){parts.add(expression.substring(start,i));start=i+keyword.length();i=start-1;}}parts.add(expression.substring(start));return parts;}
    private static int indexOfToken(String expression,String token){char quote=0;for(int i=0;i<=expression.length()-token.length();i++){char ch=expression.charAt(i);if((ch=='\''||ch=='\"')&&(i==0||expression.charAt(i-1)!='\\')){quote=quote==0?ch:quote==ch?0:quote;continue;}if(quote==0&&expression.regionMatches(true,i,token,0,token.length())&&boundary(expression,i-1)&&boundary(expression,i+token.length()))return i;}return -1;}
    private static int indexOutsideQuotes(String expression,String token){char quote=0;for(int i=0;i<=expression.length()-token.length();i++){char ch=expression.charAt(i);if((ch=='\''||ch=='\"')&&(i==0||expression.charAt(i-1)!='\\')){quote=quote==0?ch:quote==ch?0:quote;continue;}if(quote==0&&expression.startsWith(token,i))return i;}return -1;}
    private static boolean boundary(String text,int index){return index<0||index>=text.length()||Character.isWhitespace(text.charAt(index));}
    private static String value(String raw){String value=raw.trim();if(value.length()>=2&&((value.startsWith("'")&&value.endsWith("'"))||(value.startsWith("\"")&&value.endsWith("\""))))return value.substring(1,value.length()-1);return value;}
    private static Double number(String value){if(value.isBlank())return null;try{return Double.valueOf(value);}catch(NumberFormatException e){return null;}}
    private static String render(String template,String input,Map<String,Object> nodeContext,Map<String,Object> params){String r=template.replace("{{input}}",input).replace("{{prev.output}}",input);int start=0;while(start<r.length()){int index=r.indexOf("${",start);if(index<0)break;int end=r.indexOf("}",index+2);if(end<0)break;String name=r.substring(index+2,end),replacement=null;if(nodeContext!=null&&nodeContext.containsKey(name))replacement=text(nodeContext.get(name));else if(params!=null&&params.containsKey(name))replacement=text(params.get(name));if(replacement==null)start=end+1;else{r=r.substring(0,index)+replacement+r.substring(end+1);start=index+replacement.length();}}return r;}
    private static String text(Object value){return value==null?"":String.valueOf(value);}
    private record Operator(String name,int index,String token){}
}
