import axios from 'axios'

export const http=axios.create({baseURL:'/api',timeout:30000})
http.interceptors.request.use(config=>{const token=localStorage.getItem('authToken');if(token)config.headers.Authorization=`Bearer ${token}`;return config})
http.interceptors.response.use(response=>{const result=response.data;if(result.code!==0)return Promise.reject(new Error(result.message||'请求失败'));return result.data},error=>{if(error.response?.status===401){localStorage.removeItem('authToken');if(window.location.pathname!=='/login')window.location.href='/login'}return Promise.reject(new Error(error.response?.data?.message||error.message||'网络请求失败'))})

export interface DataSourceItem {id:number;name:string;type:'sqlite'|'h2'|'mysql';host?:string;port?:number;databaseName?:string;username?:string;password?:string;jdbcUrl?:string;online?:boolean;createdAt?:string}
export interface WorkflowItem {id:number;name:string;description?:string;status:'draft'|'active'|'disabled';nodeCount:number;createdAt?:string;updatedAt?:string;nodes?:WorkflowNodeDto[];config?:Record<string,unknown>}
export interface WorkflowNodeDto {id?:number;nodeKey:string;nodeType:string;name:string;positionX:number;positionY:number;config:Record<string,unknown>}
export interface RunItem {id:number;workflowId:number;workflowName?:string;status:string;startedAt:string;finishedAt?:string;logs?:string;nodeResults?:{nodeKey:string;nodeName:string;nodeType?:string;output:unknown}[]}
export interface RunListResult {list:RunItem[];total:number;page:number;size:number}
export interface ApiKeyItem {id:number;name:string;type:'llm'|'taiwei';baseUrl:string;apiKey:string;model?:string;remark?:string;createdAt?:string}
export interface ApiKeyOption {id:number;name:string;type:string;baseUrl:string;model?:string}

export const authApi={login:(username:string,password:string)=>http.post<never,{token:string;username:string}>('/auth/login',{username,password}),logout:()=>http.post('/auth/logout'),me:()=>http.get<never,{username:string}>('/auth/me')}

export const datasourceApi={list:()=>http.get<never,DataSourceItem[]>('/datasources'),create:(data:Partial<DataSourceItem>)=>http.post<never,DataSourceItem>('/datasources',data),update:(id:number,data:Partial<DataSourceItem>)=>http.put<never,DataSourceItem>(`/datasources/${id}`,data),remove:(id:number)=>http.delete(`/datasources/${id}`),test:(id:number)=>http.post(`/datasources/${id}/test`),query:(id:number,sql:string)=>http.post<never,{columns:string[];rows:Record<string,unknown>[]}>(`/datasources/${id}/query`,{sql})}
export const workflowApi={list:()=>http.get<never,WorkflowItem[]>('/workflows'),create:(data:Partial<WorkflowItem>)=>http.post<never,WorkflowItem>('/workflows',data),detail:(id:number)=>http.get<never,WorkflowItem>(`/workflows/${id}`),update:(id:number,data:Partial<WorkflowItem>)=>http.put<never,WorkflowItem>(`/workflows/${id}`,data),remove:(id:number)=>http.delete(`/workflows/${id}`),saveNodes:(id:number,nodes:WorkflowNodeDto[])=>http.put(`/workflows/${id}/nodes`,nodes),run:(id:number)=>http.post<never,{runId:number}>(`/workflows/${id}/run`),runs:(id:number)=>http.get<never,RunItem[]>(`/workflows/${id}/runs`),listRuns:(workflowId?:number,page=0,size=20)=>http.get<never,RunListResult>('/runs',{params:{...(workflowId?{workflowId}:{}),page,size}}),getRun:(id:number)=>http.get<never,RunItem>(`/runs/${id}`),cleanupZombies:(olderThanMinutes=30)=>http.post<never,{cleaned:number}>('/runs/cleanup-zombies',undefined,{params:{olderThanMinutes}}),schedule:(id:number)=>http.get<never,{cron?:string;nextFireTime?:string}>(`/workflows/${id}/schedule`)}
export const apiKeyApi={list:()=>http.get<never,ApiKeyItem[]>('/keys'),options:()=>http.get<never,ApiKeyOption[]>('/keys/options'),create:(data:Partial<ApiKeyItem>)=>http.post<never,ApiKeyItem>('/keys',data),update:(id:number,data:Partial<ApiKeyItem>)=>http.put<never,ApiKeyItem>(`/keys/${id}`,data),remove:(id:number)=>http.delete(`/keys/${id}`)}
