package com.dataanalyse.workflow.engine;

import com.dataanalyse.apikey.service.ApiKeyService;
import com.dataanalyse.common.BusinessException;
import com.dataanalyse.datasource.service.DataSourceService;
import com.dataanalyse.datasource.service.PasswordCipher;
import com.dataanalyse.llm.LlmClient;
import com.dataanalyse.workflow.entity.WorkflowNodeEntity;
import com.dataanalyse.workflow.service.WorkflowService;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

class WorkflowEngineTest {
    @Test void executesStartToEndTopologically(){WorkflowService workflows=mock(WorkflowService.class);WorkflowNodeEntity start=node("a","start","开始"),end=node("b","end","结束");when(workflows.parseConfig(start)).thenReturn(Map.of("_outgoing",List.of("b")));when(workflows.parseConfig(end)).thenReturn(Map.of());WorkflowEngine engine=new WorkflowEngine(workflows,mock(DataSourceService.class),mock(LlmClient.class),new ObjectMapper(),mock(ApiKeyService.class),mock(PasswordCipher.class));WorkflowEngine.ExecutionResult result=engine.execute(List.of(start,end),"触发值");assertEquals("触发值",result.output());assertTrue(result.logs().contains("开始"));}
    @Test void injectsContextParamsIntoTemplate(){WorkflowService workflows=mock(WorkflowService.class);WorkflowNodeEntity start=node("a","start","开始"),end=node("b","end","结束");when(workflows.parseConfig(start)).thenReturn(Map.of("_outgoing",List.of("b")));when(workflows.parseConfig(end)).thenReturn(Map.of("output","参数=${stockCode} 上游={{input}}"));WorkflowEngine engine=new WorkflowEngine(workflows,mock(DataSourceService.class),mock(LlmClient.class),new ObjectMapper(),mock(ApiKeyService.class),mock(PasswordCipher.class));WorkflowEngine.ExecutionResult result=engine.execute(List.of(start,end),"上游值",Map.of("stockCode","000001"));assertEquals("参数=000001 上游=上游值",result.output());}
    @Test void retriesTransientLlmFailures(){WorkflowService workflows=mock(WorkflowService.class);LlmClient llm=mock(LlmClient.class);WorkflowNodeEntity node=node("llm","llm","模型");when(workflows.parseConfig(node)).thenReturn(Map.of("baseUrl","http://localhost","apiKey","key","model","model","systemPrompt","system","userPrompt","user","retryCount",3));when(llm.chat(anyString(),anyString(),anyString(),anyList())).thenThrow(new BusinessException(502,"临时失败")).thenThrow(new BusinessException(502,"临时失败")).thenReturn("成功");WorkflowEngine engine=new WorkflowEngine(workflows,mock(DataSourceService.class),llm,new ObjectMapper(),mock(ApiKeyService.class),mock(PasswordCipher.class));WorkflowEngine.ExecutionResult result=engine.execute(List.of(node),null);assertEquals("成功",result.output());verify(llm,times(3)).chat(anyString(),anyString(),anyString(),anyList());}
    @Test void executesPythonAndReturnsText(){WorkflowService workflows=mock(WorkflowService.class);WorkflowNodeEntity node=node("python","python","运行 Python");when(workflows.parseConfig(node)).thenReturn(Map.of("code","print(\"hello\")"));WorkflowEngine engine=new WorkflowEngine(workflows,mock(DataSourceService.class),mock(LlmClient.class),new ObjectMapper(),mock(ApiKeyService.class),mock(PasswordCipher.class));assertEquals("hello",engine.execute(List.of(node),null).output());}
    @Test void executesPythonAndParsesJson(){WorkflowService workflows=mock(WorkflowService.class);WorkflowNodeEntity node=node("python","python","运行 Python");when(workflows.parseConfig(node)).thenReturn(Map.of("code","import json;print(json.dumps({\"a\":1}))"));WorkflowEngine engine=new WorkflowEngine(workflows,mock(DataSourceService.class),mock(LlmClient.class),new ObjectMapper(),mock(ApiKeyService.class),mock(PasswordCipher.class));Object output=engine.execute(List.of(node),null).output();assertInstanceOf(Map.class,output);assertEquals(1,((Map<?,?>)output).get("a"));}
    @Test void emptyOutputShortCircuitsToEmptyTo(){WorkflowService workflows=mock(WorkflowService.class);WorkflowNodeEntity start=node("a","start","开始"),mid=node("m","python","检查"),end=node("b","end","结束");when(workflows.parseConfig(start)).thenReturn(Map.of("_outgoing",List.of("m")));when(workflows.parseConfig(mid)).thenReturn(Map.of("_outgoing",List.of("b"),"emptyTo","b","code","print('')"));when(workflows.parseConfig(end)).thenReturn(Map.of("output","结束"));WorkflowEngine engine=new WorkflowEngine(workflows,mock(DataSourceService.class),mock(LlmClient.class),new ObjectMapper(),mock(ApiKeyService.class),mock(PasswordCipher.class));WorkflowEngine.ExecutionResult result=engine.execute(List.of(start,mid,end),"触发值");assertEquals("结束",result.output());assertTrue(result.logs().contains("输出为空，按 emptyTo 跳转到"));}
    @Test void nonEmptyOutputKeepsNormalFlow(){WorkflowService workflows=mock(WorkflowService.class);WorkflowNodeEntity start=node("a","start","开始"),mid=node("m","python","检查"),end=node("b","end","结束");when(workflows.parseConfig(start)).thenReturn(Map.of("_outgoing",List.of("m")));when(workflows.parseConfig(mid)).thenReturn(Map.of("_outgoing",List.of("b"),"emptyTo","b","code","print('有数据')"));when(workflows.parseConfig(end)).thenReturn(Map.of("output","结束"));WorkflowEngine engine=new WorkflowEngine(workflows,mock(DataSourceService.class),mock(LlmClient.class),new ObjectMapper(),mock(ApiKeyService.class),mock(PasswordCipher.class));WorkflowEngine.ExecutionResult result=engine.execute(List.of(start,mid,end),"触发值");assertEquals("结束",result.output());assertFalse(result.logs().contains("输出为空，按 emptyTo 跳转到"));}
    @Test void emptyRowsMapShortCircuitsToEmptyTo(){WorkflowService workflows=mock(WorkflowService.class);WorkflowNodeEntity start=node("a","start","开始"),sql=node("s","sqlitesql","查询"),end=node("b","end","结束");when(workflows.parseConfig(start)).thenReturn(Map.of("_outgoing",List.of("s")));when(workflows.parseConfig(sql)).thenReturn(Map.of("_outgoing",List.of("b"),"emptyTo","b","dataSourceId",1,"sql","select * from t"));when(workflows.parseConfig(end)).thenReturn(Map.of("output","结束"));DataSourceService ds=mock(DataSourceService.class);when(ds.queryForWorkflow(anyLong(),eq("sqlite"),anyString())).thenReturn(Map.of("columns",List.of("id"),"rows",List.of()));WorkflowEngine engine=new WorkflowEngine(workflows,ds,mock(LlmClient.class),new ObjectMapper(),mock(ApiKeyService.class),mock(PasswordCipher.class));WorkflowEngine.ExecutionResult result=engine.execute(List.of(start,sql,end),"触发值");assertEquals("结束",result.output());assertTrue(result.logs().contains("输出为空，按 emptyTo 跳转到"));}
    @Test void emptyShortCircuitSkipsIntermediateNodesWithoutCycleError(){WorkflowService workflows=mock(WorkflowService.class);WorkflowNodeEntity start=node("a","start","开始"),sql=node("s","sqlitesql","查询"),llm=node("l","llm","LLM不该执行"),end=node("b","end","结束");when(workflows.parseConfig(start)).thenReturn(Map.of("_outgoing",List.of("s")));when(workflows.parseConfig(sql)).thenReturn(Map.of("_outgoing",List.of("l"),"emptyTo","b","dataSourceId",1,"sql","select * from t"));when(workflows.parseConfig(llm)).thenReturn(Map.of("_outgoing",List.of("b"),"baseUrl","http://x","apiKey","k","model","m","systemPrompt","s","userPrompt","u","retryCount",0));when(workflows.parseConfig(end)).thenReturn(Map.of("output","结束"));DataSourceService ds=mock(DataSourceService.class);when(ds.queryForWorkflow(anyLong(),eq("sqlite"),anyString())).thenReturn(Map.of("columns",List.of("id"),"rows",List.of()));LlmClient llmMock=mock(LlmClient.class);WorkflowEngine engine=new WorkflowEngine(workflows,ds,llmMock,new ObjectMapper(),mock(ApiKeyService.class),mock(PasswordCipher.class));WorkflowEngine.ExecutionResult result=engine.execute(List.of(start,sql,llm,end),"触发值");assertEquals("结束",result.output());assertTrue(result.logs().contains("跳过原下游"));verify(llmMock,never()).chat(anyString(),anyString(),anyString(),anyList());}

    private WorkflowNodeEntity node(String key,String type,String name){WorkflowNodeEntity n=new WorkflowNodeEntity();n.setNodeKey(key);n.setNodeType(type);n.setName(name);return n;}
}
