import { DeleteOutlined, EditOutlined, HistoryOutlined, PlayCircleOutlined, PlusOutlined } from '@ant-design/icons'
import { Button, Card, Descriptions, message, Modal, Popconfirm, Space, Table, Tag, Typography } from 'antd'
import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import dayjs from 'dayjs'
import { RunItem, workflowApi, WorkflowItem } from '../api'

const statusMap:Record<string,{text:string;color:string}>={draft:{text:'草稿',color:'default'},active:{text:'已启用',color:'success'},disabled:{text:'已停用',color:'warning'}}
export default function AnalysisListPage(){const nav=useNavigate(),[items,setItems]=useState<WorkflowItem[]>([]),[loading,setLoading]=useState(false),[history,setHistory]=useState<RunItem[]>(),[selectedRun,setSelectedRun]=useState<RunItem>();const load=async()=>{setLoading(true);try{setItems(await workflowApi.list())}catch(e){message.error((e as Error).message)}finally{setLoading(false)}};useEffect(()=>{load()},[]);
const create=async()=>{try{const item=await workflowApi.create({name:`新建工作流 ${dayjs().format('MM-DD HH:mm')}`,status:'draft'});nav(`/analysis/${item.id}`)}catch(e){message.error((e as Error).message)}};
const showRuns=async(id:number)=>{try{setHistory(await workflowApi.runs(id))}catch(e){message.error((e as Error).message)}};
const columns=[{title:'名称',dataIndex:'name'},{title:'状态',dataIndex:'status',render:(v:string)=><Tag color={statusMap[v]?.color}>{statusMap[v]?.text??v}</Tag>},{title:'节点数',dataIndex:'nodeCount'},{title:'创建时间',dataIndex:'createdAt',render:date},{title:'更新时间',dataIndex:'updatedAt',render:date},{title:'操作',width:360,render:(_:unknown,r:WorkflowItem)=><Space><Button type="link" icon={<EditOutlined/>} onClick={()=>nav(`/analysis/${r.id}`)}>编辑</Button><Button type="link" icon={<PlayCircleOutlined/>} onClick={async()=>{try{const x=await workflowApi.run(r.id);message.success(`已启动，运行 ID：${x.runId}`)}catch(e){message.error((e as Error).message)}}}>运行</Button><Button type="link" icon={<HistoryOutlined/>} onClick={()=>showRuns(r.id)}>运行历史</Button><Popconfirm title="确认删除工作流及其运行记录？" onConfirm={async()=>{await workflowApi.remove(r.id);message.success('已删除');load()}}><Button danger type="link" icon={<DeleteOutlined/>}>删除</Button></Popconfirm></Space>}];
return <><div className="page-heading"><div><Typography.Title level={2}>数据分析</Typography.Title><Typography.Text type="secondary">绘制、调度并运行自动化数据工作流</Typography.Text></div><Button type="primary" icon={<PlusOutlined/>} onClick={create}>新建</Button></div><Card><Table rowKey="id" loading={loading} dataSource={items} columns={columns}/></Card><Modal title="运行历史" open={!!history} onCancel={()=>setHistory(undefined)} footer={null} width={900}><Table rowKey="id" dataSource={history} pagination={{pageSize:8}} columns={[{title:'运行 ID',dataIndex:'id'},{title:'状态',dataIndex:'status',render:(v:string)=><Tag color={v==='success'?'success':v==='failed'?'error':'processing'}>{v}</Tag>},{title:'开始时间',dataIndex:'startedAt',render:date},{title:'结束时间',dataIndex:'finishedAt',render:date},{title:'操作',render:(_:unknown,r:RunItem)=><Button type="link" onClick={()=>setSelectedRun(r)}>查看日志</Button>}]}/></Modal><Modal title={`运行日志 #${selectedRun?.id??''}`} open={!!selectedRun} onCancel={()=>setSelectedRun(undefined)} footer={null}><Descriptions column={1} bordered items={[{key:'s',label:'状态',children:selectedRun?.status},{key:'l',label:'日志',children:<pre className="run-log">{selectedRun?.logs}</pre>}]}/></Modal></>}
function date(v?:string){return v?dayjs(v).format('YYYY-MM-DD HH:mm:ss'):'-'}
