import { DeleteOutlined, EditOutlined, HistoryOutlined, PlusOutlined } from '@ant-design/icons'
import { Button, Card, message, Popconfirm, Space, Switch, Table, Tag, Typography } from 'antd'
import { useEffect, useState } from 'react'
import dayjs from 'dayjs'
import { workflowApi, WorkflowItem } from '../api'
import RunWorkflowButton from '../components/workflow/RunWorkflowButton'

const statusMap:Record<string,{text:string;color:string}>={draft:{text:'草稿',color:'default'},active:{text:'已启用',color:'success'},disabled:{text:'已停用',color:'warning'}}
export default function AnalysisListPage(){const [items,setItems]=useState<WorkflowItem[]>([]),[loading,setLoading]=useState(false),[monitorSaving,setMonitorSaving]=useState<number>();const load=async()=>{setLoading(true);try{setItems(await workflowApi.list())}catch(e){message.error((e as Error).message)}finally{setLoading(false)}};useEffect(()=>{load()},[]);
const create=async()=>{try{const item=await workflowApi.create({name:`新建工作流 ${dayjs().format('MM-DD HH:mm')}`,status:'draft'});window.open(`/analysis/${item.id}`,'_blank')}catch(e){message.error((e as Error).message)}};
const toggleMonitor=async(item:WorkflowItem,enabled:boolean)=>{setMonitorSaving(item.id);try{const detail=await workflowApi.detail(item.id);await workflowApi.update(item.id,{name:detail.name,description:detail.description,status:detail.status,config:{...(detail.config??{}),monitorEnabled:enabled}});setItems(current=>current.map(row=>row.id===item.id?{...row,monitorEnabled:enabled}:row));message.success(enabled?'已开启实时执行过程':'已关闭实时执行过程')}catch(e){message.error((e as Error).message)}finally{setMonitorSaving(undefined)}};
const columns=[{title:'名称',dataIndex:'name'},{title:'状态',dataIndex:'status',render:(v:string)=><Tag color={statusMap[v]?.color}>{statusMap[v]?.text??v}</Tag>},{title:'节点数',dataIndex:'nodeCount'},{title:'创建时间',dataIndex:'createdAt',render:date},{title:'更新时间',dataIndex:'updatedAt',render:date},{title:'操作',width:280,render:(_:unknown,r:WorkflowItem)=><Space direction="vertical" size={4}><Space wrap><Button type="link" icon={<EditOutlined/>} onClick={()=>window.open(`/analysis/${r.id}`,'_blank')}>编辑</Button><RunWorkflowButton workflowId={r.id} buttonType="link"/><Button type="link" icon={<HistoryOutlined/>} onClick={()=>window.open(`/runs?workflowId=${r.id}`,'_blank')}>日志</Button><Button type="link" disabled={!r.monitorEnabled} onClick={()=>window.open(`/monitor/${r.id}`,'_blank')}>监控</Button></Space><Space wrap size={6}><Space size={6}><Typography.Text>实时执行过程</Typography.Text><Switch size="small" checked={!!r.monitorEnabled} loading={monitorSaving===r.id} onChange={enabled=>toggleMonitor(r,enabled)}/></Space><Popconfirm title="确认删除工作流及其运行记录？" onConfirm={async()=>{await workflowApi.remove(r.id);message.success('已删除');load()}}><Button danger type="link" icon={<DeleteOutlined/>}>删除</Button></Popconfirm></Space></Space>}];
return <><div className="page-heading"><div><Typography.Title level={2}>数据分析</Typography.Title><Typography.Text type="secondary">绘制、调度并运行自动化数据工作流</Typography.Text></div><Button type="primary" icon={<PlusOutlined/>} onClick={create}>新建</Button></div><Card><Table rowKey="id" loading={loading} dataSource={items} columns={columns}/></Card></>}
function date(v?:string){return v?dayjs(v).format('YYYY-MM-DD HH:mm:ss'):'-'}
