import { DeleteOutlined, EditOutlined, PlusOutlined, SearchOutlined } from '@ant-design/icons'
import { Button, Card, Form, Input, InputNumber, message, Modal, Popconfirm, Radio, Space, Table, Tag, Typography } from 'antd'
import { useEffect, useState } from 'react'
import dayjs from 'dayjs'
import { datasourceApi, DataSourceItem } from '../api'

const typeNames={sqlite:'SQLite',h2:'H2',mysql:'MySQL'}
export default function DataSourcePage(){const [items,setItems]=useState<DataSourceItem[]>([]),[loading,setLoading]=useState(false),[open,setOpen]=useState(false),[editing,setEditing]=useState<DataSourceItem>(),[testing,setTesting]=useState(false),[querySource,setQuerySource]=useState<DataSourceItem>(),[sql,setSql]=useState('SELECT 1'),[queryResult,setQueryResult]=useState<{columns:string[];rows:Record<string,unknown>[]} >(),[form]=Form.useForm();const type=Form.useWatch('type',form);
const load=async()=>{setLoading(true);try{setItems(await datasourceApi.list())}catch(e){message.error((e as Error).message)}finally{setLoading(false)}};useEffect(()=>{load()},[]);
const showForm=(record?:DataSourceItem)=>{setEditing(record);form.setFieldsValue(record??{type:'sqlite',port:3306});setOpen(true)};
const save=async()=>{try{const value=await form.validateFields();if(editing)await datasourceApi.update(editing.id,value);else await datasourceApi.create(value);message.success('保存成功');setOpen(false);load()}catch(e){if(e instanceof Error)message.error(e.message)}};
const test=async()=>{try{const value=await form.validateFields();setTesting(true);let current=editing;if(current)await datasourceApi.update(current.id,value);else{current=await datasourceApi.create(value);setEditing(current)}await datasourceApi.test(current.id);message.success('连接成功');load()}catch(e){message.error((e as Error).message)}finally{setTesting(false)}};
const runQuery=async()=>{if(!querySource)return;try{setQueryResult(await datasourceApi.query(querySource.id,sql));message.success('执行成功')}catch(e){message.error((e as Error).message)}};
const columns=[{title:'名称',dataIndex:'name'},{title:'类型',dataIndex:'type',render:(v:keyof typeof typeNames)=><Tag color="blue">{typeNames[v]}</Tag>},{title:'状态',dataIndex:'online',render:(v:boolean)=><Tag color={v?'success':'error'}>{v?'在线':'离线'}</Tag>},{title:'创建时间',dataIndex:'createdAt',render:(v:string)=>v?dayjs(v).format('YYYY-MM-DD HH:mm'):'-'},{title:'操作',render:(_:unknown,r:DataSourceItem)=><Space><Button type="link" icon={<EditOutlined/>} onClick={()=>showForm(r)}>编辑</Button><Button type="link" icon={<SearchOutlined/>} onClick={()=>{setQuerySource(r);setQueryResult(undefined)}}>SQL查询</Button><Popconfirm title="确认删除该数据源？" onConfirm={async()=>{await datasourceApi.remove(r.id);message.success('已删除');load()}}><Button danger type="link" icon={<DeleteOutlined/>}>删除</Button></Popconfirm></Space>}];
return <><div className="page-heading"><div><Typography.Title level={2}>数据源管理</Typography.Title><Typography.Text type="secondary">管理外部数据库连接并直接执行 SQL 查询</Typography.Text></div><Button type="primary" icon={<PlusOutlined/>} onClick={()=>showForm()}>新建数据源</Button></div><Card><Table rowKey="id" loading={loading} dataSource={items} columns={columns}/></Card>
<Modal title={editing?'编辑数据源':'新建数据源'} open={open} onCancel={()=>setOpen(false)} onOk={save} width={620} footer={(_,o)=><><Button loading={testing} onClick={test}>测试连接</Button>{o.CancelBtn}{o.OkBtn}</>}><Form form={form} layout="vertical"><Form.Item name="name" label="名称" rules={[{required:true,message:'请输入数据源名称'}]}><Input/></Form.Item><Form.Item name="type" label="类型" rules={[{required:true}]}><Radio.Group disabled={!!editing} options={[{label:'SQLite',value:'sqlite'},{label:'H2',value:'h2'},{label:'MySQL',value:'mysql'}]}/></Form.Item>{type==='mysql'?<><Space align="start" style={{width:'100%'}}><Form.Item name="host" label="主机" rules={[{required:true}]}><Input placeholder="localhost"/></Form.Item><Form.Item name="port" label="端口"><InputNumber min={1} max={65535}/></Form.Item></Space><Form.Item name="databaseName" label="数据库名" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="username" label="用户名" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="password" label="密码"><Input.Password placeholder={editing?'留空或 *** 表示不修改':''}/></Form.Item></>:<><Form.Item name="databaseName" label={type==='sqlite'?'SQLite 文件路径':'H2 文件路径或内存库（mem:名称）'} rules={[{required:true}]}><Input placeholder={type==='sqlite'?'./data/demo.db':'./data/demo 或 mem:demo'}/></Form.Item>{type==='h2'&&<><Form.Item name="username" label="用户名"><Input placeholder="sa"/></Form.Item><Form.Item name="password" label="密码"><Input.Password/></Form.Item></>}</>}</Form></Modal>
<Modal title={`SQL 查询 · ${querySource?.name??''}`} open={!!querySource} onCancel={()=>setQuerySource(undefined)} width={900} footer={null}><Input.TextArea value={sql} onChange={e=>setSql(e.target.value)} rows={6} placeholder="请输入 SQL 语句"/><Button type="primary" onClick={runQuery} style={{margin:'12px 0'}}>运行 SQL</Button>{queryResult&&<Table size="small" scroll={{x:true,y:360}} rowKey={(_,i)=>String(i)} dataSource={queryResult.rows} columns={queryResult.columns.map(c=>({title:c,dataIndex:c,key:c,render:(v:unknown)=>typeof v==='object'?JSON.stringify(v):String(v??'')}))}/>}</Modal></>}
