import { ArrowLeftOutlined, PlayCircleOutlined, SaveOutlined } from '@ant-design/icons'
import { addEdge, Background, Connection, Controls, Edge, MiniMap, Node, ReactFlow, ReactFlowProvider, useEdgesState, useNodesState, useReactFlow } from '@xyflow/react'
import '@xyflow/react/dist/style.css'
import { Button, Drawer, Form, Input, message, Select, Space, Spin, Tag, Typography } from 'antd'
import { DragEvent, useCallback, useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { datasourceApi, DataSourceItem, workflowApi, WorkflowItem, WorkflowNodeDto } from '../api'
import WorkflowNode, { workflowNodeMeta } from '../components/workflow/WorkflowNode'

type FlowData={nodeType:string;name:string;config:Record<string,unknown>}
const nodeTypes={workflow:WorkflowNode};const palette=['start','end','taiwei','llm','h2sql','sqlitesql'];
export default function WorkflowEditorPage(){return <ReactFlowProvider><Editor/></ReactFlowProvider>}
function Editor(){const {id}=useParams(),workflowId=Number(id),nav=useNavigate(),flow=useReactFlow(),[nodes,setNodes,onNodesChange]=useNodesState<Node<FlowData>>([]),[edges,setEdges,onEdgesChange]=useEdgesState<Edge>([]),[workflow,setWorkflow]=useState<WorkflowItem>(),[sources,setSources]=useState<DataSourceItem[]>([]),[selected,setSelected]=useState<string>(),[loading,setLoading]=useState(true),[form]=Form.useForm();
useEffect(()=>{(async()=>{try{const [detail,ds]=await Promise.all([workflowApi.detail(workflowId),datasourceApi.list()]);setWorkflow(detail);setSources(ds);const loaded=(detail.nodes??[]).map(n=>({id:n.nodeKey,type:'workflow',position:{x:n.positionX,y:n.positionY},data:{nodeType:n.nodeType,name:n.name,config:n.config}}));setNodes(loaded);const loadedEdges:Edge[]=[];(detail.nodes??[]).forEach(n=>((n.config._outgoing as string[])??[]).forEach(target=>loadedEdges.push({id:`${n.nodeKey}-${target}`,source:n.nodeKey,target})));setEdges(loadedEdges)}catch(e){message.error((e as Error).message)}finally{setLoading(false)}})()},[workflowId,setEdges,setNodes]);
const selectedNode=nodes.find(n=>n.id===selected);useEffect(()=>{if(selectedNode)form.setFieldsValue({name:selectedNode.data.name,...selectedNode.data.config})},[selectedNode,form]);
const connect=useCallback((c:Connection)=>setEdges(es=>addEdge({...c,id:`${c.source}-${c.target}`},es)),[setEdges]);
const drop=(event:DragEvent)=>{event.preventDefault();const nodeType=event.dataTransfer.getData('application/dataanalyse');if(!nodeType)return;const position=flow.screenToFlowPosition({x:event.clientX,y:event.clientY});const nodeKey=`${nodeType}-${Date.now()}`;setNodes(ns=>[...ns,{id:nodeKey,type:'workflow',position,data:{nodeType,name:workflowNodeMeta[nodeType].label,config:{}}}])};
const save=async()=>{try{const dto:WorkflowNodeDto[]=nodes.map(n=>({nodeKey:n.id,nodeType:n.data.nodeType,name:n.data.name,positionX:n.position.x,positionY:n.position.y,config:{...n.data.config,_outgoing:edges.filter(e=>e.source===n.id).map(e=>e.target)}}));await workflowApi.saveNodes(workflowId,dto);message.success('工作流已保存')}catch(e){message.error((e as Error).message)}};
const updateNode=(_:unknown,all:Record<string,unknown>)=>{if(!selected)return;setNodes(ns=>ns.map(n=>n.id===selected?{...n,data:{...n.data,name:String(all.name??n.data.name),config:{...n.data.config,...all,name:undefined}}}:n))};
const activate=async(value:string)=>{if(!workflow)return;try{const next=await workflowApi.update(workflowId,{name:workflow.name,description:workflow.description,status:value as WorkflowItem['status']});setWorkflow({...workflow,...next});message.success('状态已更新')}catch(e){message.error((e as Error).message)}};
if(loading)return <div className="editor-loading"><Spin size="large"/></div>;return <div className="editor-shell"><header className="editor-toolbar"><Space><Button icon={<ArrowLeftOutlined/>} onClick={()=>nav('/analysis')}>返回</Button><div><Typography.Title level={4}>{workflow?.name}</Typography.Title><Space size={4}><Typography.Text type="secondary">状态</Typography.Text><Select size="small" value={workflow?.status} onChange={activate} style={{width:92}} options={[{label:'草稿',value:'draft'},{label:'启用',value:'active'},{label:'停用',value:'disabled'}]}/></Space></div></Space><Space><Button icon={<SaveOutlined/>} type="primary" onClick={save}>保存</Button><Button icon={<PlayCircleOutlined/>} onClick={async()=>{try{await save();const r=await workflowApi.run(workflowId);message.success(`运行已启动 #${r.runId}`)}catch(e){message.error((e as Error).message)}}}>运行</Button></Space></header><div className="editor-body"><aside className="palette"><Typography.Title level={5}>插件</Typography.Title><Typography.Text type="secondary">拖到画布添加节点</Typography.Text>{palette.map(type=>{const m=workflowNodeMeta[type];return <div key={type} className="palette-item" draggable onDragStart={e=>{e.dataTransfer.setData('application/dataanalyse',type);e.dataTransfer.effectAllowed='move'}}><span style={{color:m.color}}>{m.icon}</span><span>{m.label}</span></div>})}<div className="palette-tip"><Tag color="blue">连线</Tag><p>从节点右侧圆点拖到下一节点左侧圆点。</p></div></aside><main className="flow-wrap" onDrop={drop} onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect='move'}}><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onConnect={connect} onNodeClick={(_,n)=>setSelected(n.id)} onPaneClick={()=>setSelected(undefined)} fitView deleteKeyCode={['Backspace','Delete']}><Background/><MiniMap/><Controls/></ReactFlow></main></div><Drawer title={`配置节点 · ${selectedNode?.data.name??''}`} open={!!selectedNode} onClose={()=>setSelected(undefined)} width={440} destroyOnClose><Form form={form} layout="vertical" onValuesChange={updateNode}><Form.Item name="name" label="节点名称"><Input/></Form.Item>{selectedNode&&<NodeConfig type={selectedNode.data.nodeType} sources={sources}/>}</Form></Drawer></div>}
function NodeConfig({type,sources}:{type:string;sources:DataSourceItem[]}){if(type==='start')return <Form.Item name="cron" label="定时执行周期（cron）" extra="例如：0 0/5 * * * *"><Input placeholder="秒 分 时 日 月 周"/></Form.Item>;if(type==='end')return <Form.Item name="output" label="输出模板" extra="留空直接输出上游结果；支持 {{input}}"><Input.TextArea rows={4}/></Form.Item>;if(type==='taiwei'||type==='llm')return <><Form.Item name="baseUrl" label="Base URL" rules={[{required:true}]}><Input placeholder="https://example.com"/></Form.Item><Form.Item name="apiKey" label="API Key"><Input.Password/></Form.Item><Form.Item name="model" label="模型" rules={[{required:true}]}><Input/></Form.Item>{type==='llm'&&<Form.Item name="systemPrompt" label="系统提示词"><Input.TextArea rows={4}/></Form.Item>}<Form.Item name={type==='taiwei'?'prompt':'userPrompt'} label={type==='taiwei'?'任务提示词':'用户提示词'} extra="支持 {{input}} / {{prev.output}}"><Input.TextArea rows={7}/></Form.Item></>;if(type==='h2sql'||type==='sqlitesql'){const sourceType=type==='h2sql'?'h2':'sqlite';return <><Form.Item name="dataSourceId" label="数据源" rules={[{required:true}]}><Select placeholder="请选择数据源" options={sources.filter(s=>s.type===sourceType).map(s=>({label:s.name,value:s.id}))}/></Form.Item><Form.Item name="sql" label="SQL 语句" rules={[{required:true}]} extra="支持 {{input}} / {{prev.output}}"><Input.TextArea className="sql-editor" rows={12}/></Form.Item></>}return null}
